require("items.widgets.battery")
-- require("items.widgets.qq")
-- require("items.widgets.wechat_and_qq")
require("items.widgets.language")
require("items.widgets.volume")
require("items.widgets.wifi")
-- require("items.widgets.weather")
require("items.widgets.cpu_and_temp")
require("items.widgets.slack")
require("items.widgets.telegram")
-- require("items.widgets.front_app")
-- require("items.widgets.temperature")
-- require("items.widgets.cpu")
